[project]
name = "cpj-thesis-2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=6.29.5",
    "params>=0.9.0",
    "streamlit>=1.45.1",
    "vega-datasets>=0.9.0",
]
